### ISSUE TITLE
[IHM] maquette nouveau workflow preuve de dépot et accusé de réception

### ISSUE THREAD

**Issue by evarisk-theo** [Eoxia/doliletter#296]

**Comment by eoxia-amandine** [comment]
Version 1
![version-1](https://user-images.githubusercontent.com/18576747/162477928-4c4f143d-6e1b-4cb0-8a40-3d595f405817.png)
![version-1-2](https://user-images.githubusercontent.com/18576747/162477932-1ac033a0-4697-4754-9aa9-72a4be3d71b5.png)

Version 2 (version choisie)
![version-2](https://user-images.githubusercontent.com/18576747/162478030-3a5514de-1f09-4fe2-b2c4-a7a283636fe1.png)
