### ISSUE TITLE
Définir les informations ainsi que les étapes d'implémentation dans les versions des Signatures

### ISSUE THREAD

**Issue by eoxia-noe** [Eoxia/doliletter#51]
Les documents envoyés sont souvent signés

- Tampon de la société
- Signature
- Rien rien

1. Le cas du tampon de la société ou signature générique
Cette option pourrait être mise en place dans les réglages avec l'upload d'un fichier image
2. Le cas des signatures : 
Signature de l'utilisateur connecté ? (Ajout dans le compte utilisateur de la signature)
Question : l'utilisateur courant, qui peut être différent de la personne qui envoie?
3. Accusé réception de l'expéditeur
Le réceptionnaire peut t il signer (Comme un LRAR qui serait signé par le réceptionnaire ? cas des signatures :

**Comment by lmag** [comment]
à Définir avec l'utilisateur ainsi que les étapes possibles c'est un bon exercice :)

**Comment by lmag** [comment]
Tu as une amélioration de la description
